azure:
  activedirectory:
    # Specifies your Active Directory ID:
    tenant-id: 9457c7ae-67a9-45a0-8c44-83bb097e1ed0
    # Specifies your App Registration's Application ID:
    client-id: 49318cd6-aa0e-4550-b178-c452fa6a3794
    # Specifies your App Registration's secret key:
    client-secret: lAv8Q~hWWDhr5Bv0.z3L_~sB13wjgt0SfE8Lrcvk
    # Specifies the post-log-out-redirect-uri, where to return your app after logout.
    post-logout-redirect-uri: http://localhost:8080
    authorization-clients:
      graph:
        # Specifies the Microsoft Graph scopes that your app needs access to:
        scopes: [https://graph.microsoft.com/User.Read,https://graph.microsoft.com/Sites.Read.All]

# which routes to restrict to authenticated users only (see SecurityConfig.java):
# enter String array (comma-separated) or just one route.
# e.g. app.protect.authenticated=/route1, /route2, /route3
app:
  protect:
    authenticated: /token_details, /call_graph

# un-comment the following lines if you are deploying to a reverse proxy (e.g. Azure App Service)
# server:
#   forward-headers-strategy: native
#   tomcat:
#     remoteip:
#       protocol-header: "X-Forwarded-Proto"
#       remote-ip-header: "X-Forwarded-For"
#       internal-proxies: ".*"